#!/usr/bin/python
#importacion del serial
import serial
import rospy
from std_msgs.msg import String
from geometry_msgs.msg import Twist
PuertoSerie=serial.Serial('/dev/ttyACM0', 9600)	
class Node():
	def __init__(self):
		self.rospy=rospy
		self.rospy.init_node("nodo_control",anonymous=True)
		self.initParameters()
		self.initPublishers()
		self.main()
	def initParameters(self):	
		self.topic_ang="/angular"
		self.topic_lin="/lineal"	
		self.msg_ang=String()
		self.msg_lin=String()
		self.msg_arduino=String()
		self.rate=self.rospy.Rate(50)	
		return
	def initPublishers(self):
		self.pub_ang=self.rospy.Publisher(self.topic_ang, String, queue_size=10)
		self.pub_lin=self.rospy.Publisher(self.topic_lin, String, queue_size=10)
		return
	def main(self):
		print("Nodo bien")
		while not self.rospy.is_shutdown():
			raw = PuertoSerie.readline()
			try:
				a, b = raw.strip().split(".")
			except:
				a,b = 5, 3
			print(a,b)
			self.pub_ang.publish(a)
			self.pub_lin.publish(b)
			self.change_arduino=False
			self.rate.sleep()
if __name__=="__main__":
	try:
		print("Inciando Nodo bien bien")
		object=Node()
	except rospy.ROSInterruptException:
		print("Finalizando Nodo")
		pass
